apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: project-s3zipper
  annotations:
    iam.amazonaws.com/role: arn:aws:iam::255738809182:role/tw-jenkins-build-assets
spec:
  containers:
  - name: gitops
    image: teamwork/ops-build-images-gitops:v1.1.0
    command:
    - cat
    tty: true
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-sock
  volumes:
  - hostPath:
      path: /var/run/docker.sock
      type: ""
    name: docker-sock