{{- if .Values.serviceAccount.create -}}
{{- $scopeDict := dict "Release" $.Release "Chart" $.Chart "name" .Values.serviceAccount.name -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    {{- include "eks.labels" $scopeDict | nindent 4 }}
    {{- include "eks.selectorLabels" $scopeDict | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if not .Values.serviceAccount.automount }}
automountServiceAccountToken: false
{{- end }}
{{- end }}
