apiVersion: v1
kind: Service
metadata:
  name: {{ include "s3zipper.fullname" . }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.service.hostname }}
  labels:
    {{- include "s3zipper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
{{- if .Values.frontend.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range $cidr := .Values.service.loadBalancerSourceRanges }}
    - {{ $cidr }}
  {{- end }}
{{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "s3zipper.selectorLabels" . | nindent 4 }}
