name: Build
on:
  push:
    branches:
      - master
      - staging

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.AWS_ECR_MASTER_ACCOUNT }}.dkr.ecr.${{ vars.AWS_ECR_MASTER_REGION }}.amazonaws.com
          username: ${{ secrets.AWS_ECR_MASTER_ACCESS_KEY }}
          password: ${{ secrets.AWS_ECR_MASTER_SECRET_ACCESS_KEY }}
      
      - name: Version
        id: version
        run: |
          version=$(git rev-parse HEAD)
          echo "version=$version" >> $GITHUB_ENV

      - run: docker context create builders

      - uses: docker/setup-buildx-action@v3
        with:
          version: latest
          endpoint: builders

      - name: build
        run: |
          make -f Makefile build push BRANCH=${{ github.ref_name }} NPM_TOKEN=${{ secrets.NPM_TOKEN }} ECR_ACCOUNT=${{ vars.AWS_ECR_MASTER_ACCOUNT }} ECR_REGION=${{ vars.AWS_ECR_MASTER_REGION }}
          make -f Makefile git-prep git-push GH_TOKEN=${{ secrets.GH_ADMIN_TOKEN }} BRANCH=${{ github.ref_name }}
      
