name: Build
on:
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.AWS_ECR_MASTER_ACCOUNT }}.dkr.ecr.${{ vars.AWS_ECR_MASTER_REGION }}.amazonaws.com
          username: ${{ secrets.AWS_ECR_MASTER_ACCESS_KEY }}
          password: ${{ secrets.AWS_ECR_MASTER_SECRET_ACCESS_KEY }}
      
      - name: Version
        id: version
        run: |
          version=$(git rev-parse HEAD)
          echo "version=$version" >> $GITHUB_ENV

      - name: build
        run: |
          make -f Makefile build push BRANCH=${{ github.ref_name }} NPM_TOKEN=${{ secrets.NPM_TOKEN }} ECR_ACCOUNT=${{ vars.AWS_ECR_MASTER_ACCOUNT }} ECR_REGION=${{ vars.AWS_ECR_MASTER_REGION }}
          make -f Makefile git-prep git-push GH_TOKEN=${{ secrets.GH_ADMIN_TOKEN }} BRANCH=${{ github.ref_name }}
      
      - name: Trigger staging gitops workflow
        if: github.ref == 'refs/heads/staging'
        run: |
          version="${{ env.version }}"
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer  ${{ secrets.GH_ADMIN_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Teamwork/gitops-stg-eks/actions/workflows/179048870/dispatches \
            -d '{"ref":"master","inputs":{"app":"projects/projects-s3zipper","version":"'"$version"'"}}'
          echo "🎉 Updated staging gitops projects/projects-s3zipper to $version" >> $GITHUB_STEP_SUMMARY
      
      - name: Trigger US gitops workflow
        if: github.ref == 'refs/heads/master'
        run: |
          version="${{ env.version }}"
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer  ${{ secrets.GH_ADMIN_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Teamwork/gitops-us-eks/actions/workflows/179991878/dispatches \
            -d '{"ref":"main","inputs":{"app":"projects/projects-s3zipper","version":"'"$version"'"}}'
          echo "🎉 Updated US gitops projects/projects-s3zipper to $version" >> $GITHUB_STEP_SUMMARY
      
      - name: Trigger EU gitops workflow
        if: github.ref == 'refs/heads/master'
        run: |
          version="${{ env.version }}"
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer  ${{ secrets.GH_ADMIN_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Teamwork/gitops-eu-eks/actions/workflows/179991961/dispatches \
            -d '{"ref":"main","inputs":{"app":"projects/projects-s3zipper","version":"'"$version"'"}}'
          echo "🎉 Updated EU gitops projects/projects-s3zipper to $version" >> $GITHUB_STEP_SUMMARY
